# Generated by Django 6.0.7 on 2026-07-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='GroupCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(unique=True)),
                ('next_order', models.PositiveIntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['prefix'], name='groups_grou_prefix_08c49b_idx')],
            },
        ),
    ]
