# Generated by Django 6.0.7 on 2026-07-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_name_groupcounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcounter',
            name='next_order',
        ),
        migrations.AddField(
            model_name='groupcounter',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, editable=False, unique=True),
        ),
    ]
